#!/usr/bin/env bash
# Install and adjust HAproxy

apt-get -y update
apt-get -y upgrade

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.5
app-get -y update

apt-get -y install haproxy=2.5.\*

config="\
frontend balancer
    bind *:80
    mode http
    default_backend lb-backends

backend lb-backends
    balance roundrobin
    server 48229-web-01 54.198.74.180 check
    server 48229-web-02 34.229.56.208 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
