#!/usr/bin/env bash
# Installs HAProxy with configurations:

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 48229-web-01 54.198.74.180:80 check
    server 48229-web-02 34.229.56.208:80 check
EOT

sudo service haproxy restart
