#!/usr/bin/env bash
# Process and pid task

trap "rm /var/run/myscript.pid && echo I hate the kill command" SIGTERM
trap "rm /var/run/myscript.pid && echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid && exit" SIGQUIT

echo "$(pgrep -f 100-process_and_pid_file)" >> /var/run/myscript.pid

while :
do
	echo "To infinity and beyond"
	sleep 2
done
