#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format
# FizzBuzz multiple of 3 and 5
# Fizz multiple of 3
# Buzz mulitple of 5

for val in {1..100}
do
  if (( val % 3 == 0 && val % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( val % 3 == 0 ))
  then
    echo "Fizz"
  elif (( val % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$val"
  fi
done
