#!/usr/bin/env bash
# Displays numbers 1 - 20
#   bad luck from China for the 4th ieteration.
#   bad luck from Japan for the 9th iteration.
#   bad luck from Italy for the 17th loop iteration.

num=1
while [ $num -le 20 ]
do
  echo "$num"
  case $num in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( num++ ))
done
